name: Build Cache

# Use GitHub Pages to share Gradle Build Cache

on:
   workflow_dispatch:
   workflow_call:
   push:
      paths-ignore:
         - 'doc/**'
         - 'documentation/**'
         - '*.md'
         - '*.yml'
         - '.github/workflows/**'
      branches:
         - master


concurrency:
   group: "gradle-build-cache"
   cancel-in-progress: false


jobs:

   build:
      runs-on: windows-latest
      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v3

         -  name: Setup JDK
            uses: actions/setup-java@v3
            with:
               distribution: temurin
               java-version: 11

         -  uses: gradle/gradle-build-action@v2
            with:
               gradle-home-cache-cleanup: true
               arguments: >-
                  assemble
                  -Dkotlin.incremental=false


# jsTest
# linuxX64Test
# macosX64Test
# macosArm64Test
# iosX64Test
# iosSimulatorArm64Test
# tvosX64Test
# watchosX86Test
# watchosX64Test
# watchosSimulatorArm64Test
# tvosSimulatorArm64Test


         -  name: Bundle the build report
            if: failure()
            shell: bash
            run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

         -  name: Upload the build report
            if: failure()
            uses: actions/upload-artifact@v3
            with:
               name: error-report
               path: build-reports.zip


#         -  name: tree home
#            shell: bash
#            run: tree $HOME
#         -  name: tree home
#            shell: bash
#            run: tree ~

         -  uses: actions/upload-pages-artifact@v1
            with:
               path: /home/runner/.gradle/caches/build-cache-1

   deploy:
      needs: build
      runs-on: ubuntu-latest
      permissions:
         pages: write      # to deploy to Pages
         id-token: write   # to verify the deployment originates from an appropriate source
      environment:
         name: github-pages
         url: ${{ steps.deployment.outputs.page_url }}
      steps:
         -  name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v1
